theme = "modern"
icons = "awesome5"

[[block]]
block = "time"

[[block]]
block = "battery"
good = 80
warning = 40
critical = 20

[[block]]
block = "sound"
driver = "pulseaudio"
headphones_indicator = true
show_volume_when_muted = true
