# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1e1e2e'
foreground='#d9e0ee'

# Colors
color0='#6e6c7e'
color1='#f28fad'
color2='#abe9b3'
color3='#fae3b0'
color4='#96cdfb'
color5='#ddb6f2'
color6='#f5c2e7'
color7='#c3bac6'
color8='#988ba2'
color9='#f28fad'
color10='#abe9b3'
color11='#fae3b0'
color12='#96cdfb'
color13='#ddb6f2'
color14='#f5c2e7'
color15='#d9e0ee'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
